In [13]:
import numpy as np

In [1]:
a= np.random.random((3,3))
a

<IPython.core.display.Javascript object>

array([[0.7016818 , 0.21259821, 0.60396346],
       [0.86875766, 0.31900807, 0.65997601],
       [0.12027275, 0.89444447, 0.15296874]])

In [2]:
b= np.random.random((3,3))
b

<IPython.core.display.Javascript object>

array([[0.71307791, 0.19682525, 0.59389261],
       [0.51616006, 0.25771742, 0.2668007 ],
       [0.97287092, 0.3286599 , 0.12038467]])

# 1. Write a Python Program to Add Two Matrices?

In [3]:
a+b

array([[1.4147597 , 0.40942346, 1.19785607],
       [1.38491772, 0.57672549, 0.92677671],
       [1.09314366, 1.22310437, 0.27335341]])

# 2. Write a Python Program to Multiply Two Matrices

In [4]:
a@b

array([[1.19766697, 0.39139752, 0.54615292],
       [1.42622258, 0.47011503, 0.68051132],
       [0.69625919, 0.30446132, 0.3284826 ]])

# 3. Write a Python Program to Transpose a Matrix?

In [5]:
a.T

array([[0.7016818 , 0.86875766, 0.12027275],
       [0.21259821, 0.31900807, 0.89444447],
       [0.60396346, 0.65997601, 0.15296874]])

In [6]:
b.transpose()

array([[0.71307791, 0.51616006, 0.97287092],
       [0.19682525, 0.25771742, 0.3286599 ],
       [0.59389261, 0.2668007 , 0.12038467]])

# 4.  Write a Python Program to Sort Words in Alphabetic Order?

In [13]:
def srt(a):
    inp= a.split()
    inp.sort()
    print(inp)
    for i in inp:
        print(i)
    
srt(input('enter your string :'))
    

enter your string :my name is sachin
['is', 'my', 'name', 'sachin']
is
my
name
sachin


# 5. Write a Python Program to Remove Punctuation From a String?

In [19]:
punctuation = """!()-[]{};:'"\,<>./?@#$%^&*_~"""
def remove_punctuation(inp):
    string=''
    for i in inp:
        if i not in punctuation:
            string = string+i
    print(string)
remove_punctuation(input('enter string :'))

enter string :my [name] [is#] //Sachin//
my name is Sachin
